Form/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('authentication/', include("authentication.urls")),
    path('todo/', include("todo.urls")),
    path('weather/', include("weather.urls")),
    path('gallery/', include("gallery.urls")),
    path('blog/', include("blog.urls")),
    path('youtube/', include("youtube.urls")),
    path('catalog/', include("ecommerce_catalog.urls")),
    path('user/', include("user.urls")),
    path('logic/', include("logic.urls")),
    path('user_authentication/', include("authentication.urls")),
    path('custom_widgets/', include("custom_widgets.urls")),
    path('recipe/', include("recipe.urls")),
    # path('api-auth/', include("rest_framework.urls")),
    path('api/', include("apis.urls")),
    path('quiz/', include("quiz.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

user/urls.py
from django.urls import path
from user import views as user_view
from django.contrib.auth import views as auth
from . import views
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', Login, name="login"),
    path('logout/', auth.LogoutView.as_view(template_name="user/index.html"), name="logout"),
    path('register/', register, name="register"),
    path('', views.index, name="index"),
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()
	phone_no = forms.CharField(max_length = 20)
	first_name = forms.CharField(max_length = 20)
	last_name = forms.CharField(max_length = 20)
	class Meta:
		model = User
		fields = ['username', 'email', 'phone_no', 'password1', 'password2']

user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserRegisterForm
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context

# Create your views here.
def index(request):
	return render(request, 'user/index.html', {'title':'index'})

########### register here ##################################### 
def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			email = form.cleaned_data.get('email')
			######################### mail system #################################### 
			htmly = get_template('user/Email.html')
			d = { 'username': username }
			subject, from_email, to = 'welcome', 'your_email@gmail.com', email
			html_content = htmly.render(d)
			msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
			msg.attach_alternative(html_content, "text/html")
			msg.send()
			################################################################## 
			messages.success(request, f'Your account has been created ! You are now able to log in')
			return redirect('user:login')
	else:
		form = UserRegisterForm()
	return render(request, 'user/register.html', {'form': form, 'title':'register here'})

################ login forms################################################### 
def Login(request):
	if request.method == 'POST':

		# AuthenticationForm_can_also_be_used__

		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username = username, password = password)
		if user is not None:
			form = login(request, user)
			messages.success(request, f' welcome {username} !!')
			return redirect('user:index')
		else:
			messages.info(request, f'account done not exit plz sign in')
	form = AuthenticationForm()
	return render(request, 'user/login.html', {'form':form, 'title':'log in'})

user/templates/user/Email.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title></title>
		<style>
			@import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900');
		</style>
	</head>
	<body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
		<div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
			<section style="margin: 0 15px;color:#425b76;">
				<h2 style="margin: 40px 0 27px 0;text-align: center;">Thank you to registration</h2>
				<hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
				<p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Hi {{username}}, we have received your details and will process soon.</p>
			</section>
		</div>
	</body>
</html>

user/templates/user/index.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="title" content="project">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="language" content="English">
<meta name="author" content="vinayak sharma">

<title>{{title}}</title>


<!-- bootstrap file -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- bootstrap file-->

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<!-- main css -->
<link rel="stylesheet" type="text/css" href="{% static "index.css" %}" />


<!-- message here -->

{% if messages %}
{% for message in messages %}

<script>
	alert("{{ message }}");
</script>

{% endfor %}
{% endif %}

<!--_______________________________________________-->



</head>

<body class="container-fluid">


<header class="row">

	<!-- navbar-->
	<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
		<button class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" class="styleheader" href="{% url "user:index" %}">project</a>
		</div>
		<div class="collapse navbar-collapse" id="mainNavBar">
		<ul class="nav navbar-nav navbar-right">
			<li><a href="{% url "user:index" %}">Home</a></li>

			{% if user.is_authenticated %}
            <form method="post" action="{% url 'user:logout' %}">
                {% csrf_token %}
                <button type="submit"><span class="glyphicon glyphicon-log-out"></span> Logout</button>
            </form>
			<!-- <li><a href="{% url "user:logout" %}"><span class="glyphicon glyphicon-log-out"></span>  Logout</a></li> -->
			{% else %}
			<li><a href="{% url "user:register" %}"><span class="glyphicon glyphicon-user"></span>  Sign up</a></li>
			<li><a href="{% url "user:login" %}"><span class="glyphicon glyphicon-log-in"></span>  Log in</a></li>
			{% endif %}

		</ul>
		</div>
	</div>
	</nav>
</header>
<br/>
<br>
<br>
<div class="row">
	{% block start %}
	{% if user.is_authenticated %}
	<center><h1>welcome back {{user.username}}!</h1></center>
	{% else %}
	<center><h1>log in, plz . . .</h1></center>
	{% endif %}
	{% endblock %}
</div>
</body>

</html>

user/templates/user/login.html
{% extends "user/index.html" %}
{% load crispy_forms_tags %}
{% block start %}

<div class="content-section col-md-8 col-md-offset-2">
<center>
<form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
	{% csrf_token %}
	<fieldset class="form-group">
	{{ form|crispy}}
	</fieldset>
<center>
	<button style="background: black; font-size: 2rem; padding:1%;" class="btn btn-outline-info" type="submit"><span class="glyphicon glyphicon-log-in"></span>  login</button>
</center>
<br/>
<sub style="text-align: left;"><a href="{% url 'user:register' %}" style="text-decoration: none; color: blue; padding:2%; cursor:pointer; margin-right:2%;">don't have account,sign up</a></sub>
</form>
</center>
</div>
{% endblock start %}

user/templates/user/register.html
{% extends "user/index.html" %}
{% load crispy_forms_tags %}
{% block start %}

<div class="content-section col-md-8 col-md-offset-2">
<form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
	{% csrf_token %}
	<fieldset class="form-group">
	{{ form|crispy}}
	</fieldset>
	<center>
	<button style="background: black; padding:2%; font-size: 2rem; color:white;" class="btn btn-outline-info" type="submit"><span class="glyphicon glyphicon-check"></span>  sign up</button>
	</center>
	<br />
	<sub><a href="{% url 'user:login' %}" style="text-decoration: none; color: blue; padding:3%; cursor:pointer;">Already have an account ?</a></sub>
</form>
</div>
{% endblock start %}